### ISSUE TITLE
I need your help，bro!

### ISSUE THREAD

**Issue by Will-CUHKSZ** [230Twister/Unchanged#1]
I can't run your code.
The project didn't have files (.obj)

**Comment by oscarab** [comment]
readme中也提供了模型下载地址

链接: https://pan.baidu.com/s/1qrH2mZREJh0S7sOwAYYoWg?pwd=rp6k 提取码: rp6k

**Comment by Will-CUHKSZ** [comment]
Cheer！This is so kind of you！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "230Twister/Unchanged"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [230Twister/Unchanged] I need your help，bro! (Issue #1)





 
链接: https://pan.baidu.com/s/1qrH2mZREJh0S7sOwAYYoWg?pwd=rp6k 提取码: rp6k

**Comment by Will-CUHKSZ** [comment]
你好，我想学习你们的这个项目，请问你们有讲解代码的说明文档吗？急需，万分感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "230Twister/Unchanged"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [230Twister/Unchanged] I need your help，bro! (Issue #1)





 
链接: https://pan.baidu.com/s/1qrH2mZREJh0S7sOwAYYoWg?pwd=rp6k 提取码: rp6k

**Comment by Will-CUHKSZ** [comment]
你好，我已经成功运行该项目，想学习你们的这个项目，请问你们有讲解代码的说明文档吗？急需，万分感谢！


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "230Twister/Unchanged"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [230Twister/Unchanged] I need your help，bro! (Issue #1)





 
链接: https://pan.baidu.com/s/1qrH2mZREJh0S7sOwAYYoWg?pwd=rp6k 提取码: rp6k

**Comment by edw4rdyao** [comment]
@Lucky-five 您好，感谢您对我们的项目感兴趣，我们没有具体的代码说明文档，只有代码内的注释，且由于我们小组成员目前精力有限，尚未有写文档的打算，请谅解。

我们可以给您一些当时的参考资料，希望对您有帮助：
- learn opengl: https://learnopengl-cn.github.io/
- water render: https://hehao98.github.io/posts/2018/04/ocean-3/
- blender: https://www.blender.org/
- game reference: https://store.steampowered.com/app/304930/Unturned/
- bullet3: https://github.com/bulletphysics/bullet3
